[project]
name = "stock-price-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "plotly>=6.1.2",
    "streamlit>=1.46.0",
    "ta>=0.11.0",
    "yfinance>=0.2.63",
]
